Basic Todo Setup
Betra/Just-Do-It pull request #1
Opened 2019-03-27 14:36 UTC by Betra

2019-03-27 18:26 UTC, fletcherist requested changes

2019-03-27 18:26 UTC, fletcherist commented on src/components/AddTodoButton/AddTodoButton.tsx
> +export const AddTodoButton = ({ value = "Submit", onClick }: button) => (
ну такое. у тебя `any` стоит и если не придёт ничего то будет исключение. тогда пиши `onClick = () => null`
или сделай себе функцию такую `const noop = () => null` и юзай везде

2019-03-27 18:26 UTC, fletcherist commented on src/components/AddTodoButton/AddTodoButton.tsx
> +interface button {
интерфейцсы всегда с большой буквы, как и классы

2019-03-27 18:26 UTC, fletcherist commented on src/components/AddTodoButton/AddTodoButton.tsx
> +  onClick: any;
any для слабаков. в данном случае у тебя тут `onClick: (event: React.MouseEvent) => any`

2019-03-27 18:26 UTC, fletcherist commented on src/components/AddTodoInput/AddTodoInput.tsx
> +interface inputTodo {
большая буква

2019-03-27 18:26 UTC, fletcherist commented on src/store/reducers/todos.tsx
> +const todo = (state, action: actionTodo) => {
state implicit type

2019-03-30 16:01 UTC, Betra commented on src/components/AddTodoButton/AddTodoButton.tsx
> +interface button {
Fixed

2019-03-30 16:01 UTC, Betra commented on src/components/AddTodoButton/AddTodoButton.tsx
> +  onClick: any;
Fixed

2019-03-30 16:01 UTC, Betra commented on src/components/AddTodoInput/AddTodoInput.tsx
> +interface inputTodo {
Fixed

2019-03-30 16:01 UTC, Betra commented on src/store/reducers/todos.tsx
> +const todo = (state, action: actionTodo) => {
Fixed

2019-03-30 16:02 UTC, Betra commented on src/components/AddTodoButton/AddTodoButton.tsx
> +export const AddTodoButton = ({ value = "Submit", onClick }: button) => (
Fixed?

2019-04-05 07:07 UTC, merged